[
  "spotify"
  "megasync"
  "zerotierone"
  "code"
  "vscode"
  "vscode-extension-MS-python-vscode-pylance"
  "vscode-extension-github-copilot"
  "vscode-extension-ms-vscode-remote-remote-ssh"
  "gh-copilot"
]
