name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check:
    name: Nix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix develop --command nixfmt -c .
      - run: nix flake check

  system-cache:
    name: Cache full system derivations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: cofob
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivations
        run: |
          nix build .#system-cache
