name: Codestyle

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install GitPython requests
        # Dirty hack to install fmt package
        sudo wget https://cloudflare-ipfs.com/ipfs/bafybeidurvin4omcmqjks37lyw4g4uao7cupqv4imrrlxv6ywrldk3stxy/nixpkgs-fmt -O /usr/bin/nixpkgs-fmt
        sudo chmod u+x /usr/bin/nixpkgs-fmt

    - name: Apply codestyle
      run: |
        sudo nixpkgs-fmt .

        python .github/commit_and_push.py \
          --token ${{ secrets.GITHUB_TOKEN }} \
          fire-square/mineflake \
          ${{ github.head_ref || github.ref_name }} \
          "Apply codestyle :pencil2:"
